### ISSUE TITLE
Notified By User : BH Utilization report failure

### ISSUE THREAD

**Issue by sarveshreddy-tm** [puneet-tm/wirelessone-support#46] opened 2019-02-06 10:43 UTC
not getting BH utilization graph over W1 for the below mentioned Huawei switches. 

10.175.72.226
10.175.72.87
10.175.72.130
10.175.72.66
10.175.129.2
10.175.72.181
10.175.73.105
10.175.128.66

**Comment by sohailshaikh-tm** [comment] 2019-02-07 22:13
For above cases BH utilization values and graph is generating on w1.

Below are the new cases with same issue, 
Check below Huawei switches, all are responding to the SNMP but utilization values not coming on Wirelessone.


**BH Configured On IP**
10.175.152.18
10.175.88.212
10.175.90.4
10.175.73.66
172.21.220.75
10.175.84.180
10.175.8.130
10.175.144.82
10.175.89.246
10.175.65.195
10.175.73.104
10.175.34.132

**Comment by rupalivaidya-tm** [comment] 2019-02-08 11:17
The issue is resolved.

**RCA:** After changing some configuration for Huawei devices configured on ospf1_slave_7 which will prevent the trailing issue.

**Comment by rupalivaidya-tm** [comment] 2019-02-14 07:10
rohitgupta-tm : Please check and close this issue.

**Closed as completed** 2019-02-18 07:12 UTC
Labels: bug, Resolved
